research_task:
  description: >
    Perform a real-time technical and fundamental analysis for the stock: {share_name}.
    Collect and evaluate key financial indicators including current price, P/E ratio, trading volume, 52-week high/low, MACD, RSI, Debt-to-Equity ratio, and Year-over-Year Earnings Growth.
    Based on the data, generate a concise 1-line buy/sell/hold recommendation supported by metrics.

  expected_output: >
    A structured markdown report that includes:
      - 📌 **Stock Name**
      - ✅ **Key Financial & Technical Stats** (Price, P/E, Volume, High/Low, Debt/Equity, Earnings Growth)
      - 💡 **1-Line Investment Recommendation**
      - 📊 **RSI Reading**
      - 📈 **MACD Indicator**

  agent: researcher


reporting_task:
  description: >
    Use the research findings to generate a clear and informative market summary report.
    Each section should explain the stock/sector, why it was selected, key financial metrics, potential growth, and any market risks.
    The language should be beginner-friendly while still providing solid insights for potential investors or analysts.
  expected_output: >
    A markdown-formatted report with one section per stock or sector.
    Each section should include a headline, summary paragraph, key stats (e.g., 52-week high/low, P/E ratio, volume), pros and cons, and investment notes.
  agent: reporting_analyst

decider_task:
  description: >
    Review the detailed market research and expert analysis of the stock {share_name}.
    Based on this information, make a final recommendation: BUY, SELL, or HOLD.
    Support your decision with 2-3 key points from the research or analysis.
    Consider technical indicators, market sentiment, price trends, and overall outlook.
  expected_output: >
    A clear recommendation: BUY / SELL / HOLD {share_name}, followed by a short explanation of why.
  agent: decider_agent
